/** Get Dashboard Chart data */
export const API_SUCCESS = "API_SUCCESS";
export const API_FAIL = "API_FAIL";
export const GET_CHARTS_DATA = "GET_CHARTS_DATA";
export const GET_COURSE = 'GET_COURSE'

export const CHANGE_STATUS_COURSE = 'CHANGE_STATUS_COURSE'
export const CHANGE_STATUS_COURSE_SUCCESS = 'CHANGE_STATUS_COURSE_SUCCESS'
export const CHANGE_STATUS_COURSE_FAIL = 'CHANGE_STATUS_COURSE_FAIL'